### ISSUE TITLE
Multiple Questions.

### ISSUE THREAD

**Issue by ghost** [Crunchyroll-Plus/crunchyroll-docs#1]
Firstoff since i plan to use this to create a C# API Wrapper and i prolly get more Questions, it would be cool to talk you @Derro8 directly via Discord. (My Tag: elry.moe)

### Request Headers:
What do i do with the ETP-Anonymous-ID ? Where is ETP_ID coming from ?

Do i give the Authorization field the full
"Basic bm9haWhkZXZtXzZpeWcwYThsMHE6" 
or just "bm9haWhkZXZtXzZpeWcwYThsMHE6" ?

### Request Body
What to put as deviceName, deviceId & deviceType ? Im creating a multiplattform App.

**Comment by Derro8** [comment]
ETP-Anonymous-ID is your deviceId and your deviceId is a random 4uuid that whatever client you're using will generate and save so it doesn't really matter what you use for it as long as it's something like this "925eb9e2-062c-4dc3-9fd9-a2325b12d24b".

deviceName and deviceType can also be whatever you want it to be but it's not restricted to a 4uuid, you can also just not include them all they do is add some extra identifiers to the devices in https://www.crunchyroll.com/account/devices.

For authorization headers use the entirety of "Basic bm9haWhkZXZtXzZpeWcwYThsMHE6", the "Basic" part is the token type.

My discord is chonkiest_chonk if you'd like to talk on there about anything CR related. (If you're looking at this for possible help join the [discord server](https://discord.gg/9YV8rH2ntz) instead and open a ticket if you add me there is a huge chance I'll ignore it)

**Comment by ghost** [comment]
Thanks for the info, i will use the info and i added you for future questions.
