### ISSUE TITLE
Trying to make a request

### ISSUE THREAD

**Issue by alexandremerched** [Crunchyroll-Plus/crunchyroll-docs#2]
I was trying to delete rating using your API, but I just got a 403 error.

This is the URL that I tried: https://www.crunchyroll.com/content-reviews/v2/user/${userId}/rating/series/GG5H5XQ7D.

I was using Insomnia and I tried to put a Bearer token that I got in the Network Tab when I did some requests on Crunchyroll.

Can you give me a light?

**Comment by Derro8** [comment]
You'll have to replace `${userId}` with your account's id.

You can get your account's id from https://www.crunchyroll.com/accounts/v1/me

**Comment by HarshitKumar9030** [comment]
hey what about the auth token?
